import { db } from "./db";
import { places } from "@shared/schema";

const samplePlaces = [
  {
    name: "Eiffel Tower",
    description: "Iconic iron lattice tower on the Champ de Mars in Paris, France. A global cultural icon and one of the most recognizable structures in the world.",
    category: "historical",
    latitude: 48.8584,
    longitude: 2.2945,
    city: "Paris",
    country: "France",
    address: "Champ de Mars, 5 Avenue Anatole France",
    imageUrl: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800",
    entryFee: "28 EUR",
    visitDuration: "2-3 hours",
    bestTime: "Sunset",
    isPopular: true,
  },
  {
    name: "Central Park",
    description: "A sprawling urban park in the heart of Manhattan, offering green spaces, walking trails, and iconic landmarks.",
    category: "park",
    latitude: 40.7829,
    longitude: -73.9654,
    city: "New York",
    country: "USA",
    address: "Central Park, Manhattan",
    imageUrl: "https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=800",
    entryFee: "Free",
    visitDuration: "3-4 hours",
    bestTime: "Morning",
    isPopular: true,
  },
  {
    name: "Colosseum",
    description: "An ancient amphitheater in Rome, the largest ancient amphitheater ever built, and a symbol of Imperial Rome.",
    category: "historical",
    latitude: 41.8902,
    longitude: 12.4922,
    city: "Rome",
    country: "Italy",
    address: "Piazza del Colosseo, 1",
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
    entryFee: "16 EUR",
    visitDuration: "2-3 hours",
    bestTime: "Early morning",
    isPopular: true,
  },
  {
    name: "Louvre Museum",
    description: "World's largest art museum and historic monument in Paris. Home to the Mona Lisa and thousands of other masterpieces.",
    category: "museum",
    latitude: 48.8606,
    longitude: 2.3376,
    city: "Paris",
    country: "France",
    address: "Rue de Rivoli",
    imageUrl: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800",
    entryFee: "17 EUR",
    visitDuration: "4-6 hours",
    bestTime: "Wednesday or Friday evening",
    isPopular: true,
  },
  {
    name: "Tokyo Tower",
    description: "A communications and observation tower inspired by the Eiffel Tower, offering panoramic views of Tokyo.",
    category: "historical",
    latitude: 35.6586,
    longitude: 139.7454,
    city: "Tokyo",
    country: "Japan",
    address: "4 Chome-2-8 Shibakoen",
    imageUrl: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800",
    entryFee: "1200 JPY",
    visitDuration: "1-2 hours",
    bestTime: "Night",
    isPopular: true,
  },
  {
    name: "Santorini Beaches",
    description: "Stunning volcanic beaches with unique black and red sands, crystal clear waters, and dramatic cliff views.",
    category: "beach",
    latitude: 36.3932,
    longitude: 25.4615,
    city: "Santorini",
    country: "Greece",
    address: "Perissa Beach, Santorini",
    imageUrl: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800",
    entryFee: "Free",
    visitDuration: "Half day",
    bestTime: "Summer months",
    isPopular: true,
  },
  {
    name: "British Museum",
    description: "A public museum dedicated to human history, art, and culture with over 8 million works in its permanent collection.",
    category: "museum",
    latitude: 51.5194,
    longitude: -0.1270,
    city: "London",
    country: "UK",
    address: "Great Russell Street",
    imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
    entryFee: "Free",
    visitDuration: "3-4 hours",
    bestTime: "Weekday morning",
    isPopular: true,
  },
  {
    name: "Shibuya Crossing",
    description: "The world's busiest pedestrian crossing, a symbol of Tokyo's organized chaos and vibrant city life.",
    category: "historical",
    latitude: 35.6595,
    longitude: 139.7004,
    city: "Tokyo",
    country: "Japan",
    address: "2 Chome-2-1 Dogenzaka",
    imageUrl: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800",
    entryFee: "Free",
    visitDuration: "30 minutes",
    bestTime: "Evening rush hour",
    isPopular: true,
  },
  {
    name: "La Boqueria Market",
    description: "A large public market with an entrance from La Rambla, offering fresh produce, seafood, and local delicacies.",
    category: "restaurant",
    latitude: 41.3819,
    longitude: 2.1719,
    city: "Barcelona",
    country: "Spain",
    address: "La Rambla, 91",
    imageUrl: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800",
    entryFee: "Free",
    visitDuration: "1-2 hours",
    bestTime: "Morning",
    isPopular: true,
  },
  {
    name: "Sydney Opera House",
    description: "An iconic multi-venue performing arts centre, a masterpiece of 20th century architecture.",
    category: "historical",
    latitude: -33.8568,
    longitude: 151.2153,
    city: "Sydney",
    country: "Australia",
    address: "Bennelong Point",
    imageUrl: "https://images.unsplash.com/photo-1523059623039-a9ed027e7fad?w=800",
    entryFee: "45 AUD",
    visitDuration: "2-3 hours",
    bestTime: "Sunset",
    isPopular: true,
  },
  {
    name: "Grand Canyon",
    description: "A steep-sided canyon carved by the Colorado River, showcasing millions of years of geological history.",
    category: "park",
    latitude: 36.0544,
    longitude: -112.1401,
    city: "Grand Canyon Village",
    country: "USA",
    address: "Grand Canyon National Park",
    imageUrl: "https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800",
    entryFee: "35 USD per vehicle",
    visitDuration: "Full day",
    bestTime: "Spring or Fall",
    isPopular: true,
  },
  {
    name: "Bondi Beach",
    description: "One of Australia's most famous beaches, known for its golden sand, great surf, and vibrant beach culture.",
    category: "beach",
    latitude: -33.8915,
    longitude: 151.2767,
    city: "Sydney",
    country: "Australia",
    address: "Bondi Beach, NSW",
    imageUrl: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800",
    entryFee: "Free",
    visitDuration: "Half day",
    bestTime: "Summer",
    isPopular: true,
  },
  {
    name: "Tsukiji Outer Market",
    description: "A vibrant market area with restaurants, shops, and fresh seafood vendors, great for food lovers.",
    category: "restaurant",
    latitude: 35.6654,
    longitude: 139.7707,
    city: "Tokyo",
    country: "Japan",
    address: "4 Chome-16-2 Tsukiji",
    imageUrl: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800",
    entryFee: "Free",
    visitDuration: "2-3 hours",
    bestTime: "Early morning",
    isPopular: false,
  },
  {
    name: "Sagrada Familia",
    description: "Antoni Gaudi's unfinished masterpiece, a breathtaking basilica blending Gothic and Art Nouveau forms.",
    category: "historical",
    latitude: 41.4036,
    longitude: 2.1744,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer de Mallorca, 401",
    imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800",
    entryFee: "26 EUR",
    visitDuration: "2-3 hours",
    bestTime: "Morning light",
    isPopular: true,
  },
  {
    name: "Hyde Park",
    description: "One of London's largest parks, perfect for picnics, boat rides on the Serpentine, and leisurely walks.",
    category: "park",
    latitude: 51.5073,
    longitude: -0.1657,
    city: "London",
    country: "UK",
    address: "Hyde Park, London",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    entryFee: "Free",
    visitDuration: "2-3 hours",
    bestTime: "Spring",
    isPopular: false,
  },
];

async function seed() {
  console.log("Starting seed...");
  
  try {
    const existing = await db.select().from(places);
    
    if (existing.length > 0) {
      console.log(`Database already has ${existing.length} places. Skipping seed.`);
      return;
    }

    for (const place of samplePlaces) {
      await db.insert(places).values(place);
      console.log(`Added: ${place.name}`);
    }

    console.log(`Seed complete! Added ${samplePlaces.length} places.`);
  } catch (error) {
    console.error("Seed error:", error);
    throw error;
  }
}

seed().then(() => process.exit(0)).catch(() => process.exit(1));
